apiVersion: v1 
kind: Pod
metadata: 
  name: annotations
  annotations: 
  imageregistry: "https://hub.docker.com"
  buildurl: "https://github.com"
spec:
  containers:
  - name: nginx
    image: nginx