apiVersion: v1 
kind: Pod
metadata:
  name: limits
spec:
  containers:
  - name: nginx
    image: nginx
    resources:
      requests:
        cpu: "100m"
        memory: "120Mi"
      limits:
        cpu: "120Mi"
        memory: "150Mi"