apiVersion: v1 
kind: Pod
metadata:
  name: pod-config
spec:
  containers:
  - name: nginx
    image: nginx
    env:
    - name: ABC
      valueFrom:
        configMapKeyRef:
          name: nginx-config
          key: username
    - name: bcd 
      valueFrom:
        configMapKeyRef:
          name: nginx-config
          key: course