apiVersion: v1 
kind: Service
metadata:
  name: nginx
spec:
  type: NodePort
  selector:
    project: expense
    module: backend
    environment: dev
  ports:
  - name: nginx-svc-port
    port: 80
    protocol: TCP
    targetPort: 80